walls = [
    { left = 70, bottom = 168, right = 150, top = 623, degree = 1.570796 },
    { left = 1463, bottom = 168, right = 1545, top = 623, degree = 1.570796 },
    { left = 203, bottom = 663, right = 760, top = 728, degree = 0 },
    { left = 852, bottom = 663, right = 1412, top = 728, degree = 0 },
    { left = 203, bottom = 63, right = 760, top = 128, degree = 0 },
    { left = 852, bottom = 63, right = 1412, top = 128, degree = 0 }
]


holes = [
    { x = 140, y = 670 },
    { x = 808, y = 690 },
    { x = 1470, y = 670 },
    { x = 140, y = 120 },
    { x = 808, y = 100 },
    { x = 1470, y = 120 },
]


white_ball = { x = 1200, y = 400, image_x = 3, image_y = 0 }

stage1_balls = [
    { x = 500, y = 400, image_x = 0, image_y = 3 },
    { x = 460, y = 420, image_x = 1, image_y = 3 },
    { x = 460, y = 380, image_x = 2, image_y = 3 }
]


stage2_balls = [
    { x = 500, y = 400, image_x = 0, image_y = 3 },
    { x = 460, y = 420, image_x = 1, image_y = 3 },
    { x = 460, y = 380, image_x = 2, image_y = 3 },
    { x = 420, y = 440, image_x = 3, image_y = 3 },
    { x = 420, y = 400, image_x = 0, image_y = 2 },
    { x = 420, y = 360, image_x = 1, image_y = 2 },
]


stage3_balls = [
    { x = 500, y = 400, image_x = 0, image_y = 3 },
    { x = 460, y = 420, image_x = 1, image_y = 3 },
    { x = 460, y = 380, image_x = 2, image_y = 3 },
    { x = 420, y = 440, image_x = 3, image_y = 3 },
    { x = 420, y = 400, image_x = 0, image_y = 2 },
    { x = 420, y = 360, image_x = 1, image_y = 2 },

    { x = 380, y = 460, image_x = 2, image_y = 2 },
    { x = 380, y = 420, image_x = 3, image_y = 2 },
    { x = 380, y = 380, image_x = 0, image_y = 1 },
    { x = 380, y = 340, image_x = 1, image_y = 1 },
]